### ISSUE TITLE
学长 or 学姐能留下联系方式吗，有问题请教

### ISSUE THREAD

**Issue by LopSdir** [Leeyuxun/Leeyuxun.github.io#1]
您好，学长or 学姐，我也是北邮的，目前看到您的 图像加密和我做的很像，所以想请教一下，感谢

**Comment by Leeyuxun** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    你好，我GitHub仓库里的是图像同态加密，不知你是否也是做同态加密
    
      
    
        
            
    
        
        
            
                
                    李钰璕
                    
                    
                                
                                    
                                
                                
                                    ***@***.***
 
    

    在2021年04月4日 ***@***.***> 写道： 




您好，学长or 学姐，我也是北邮的，目前看到您的 图像加密和我做的很像，所以想请教一下，感谢



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LopSdir** [comment]
是的是的，怎么看不见邮箱呢，我的 qq是 519957000，能加下吗，或者我加你也行

**Comment by Leeyuxun** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    QQ：1791468501
    
      
    
        
            
    
        
        
            
                
                    李钰璕
                    
                    
                                
                                    
                                
                                
                                    ***@***.***
                                
                                
                                    
                                
                                
                                    
                                
                                
                                    
                                
                
            
        
        
    


        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2021年04月5日 ***@***.***> 写道： 




是的是的，怎么看不见邮箱呢，我的 qq是 519957000，能加下吗，或者我加你也行



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
